# Generated by Django 3.0 on 2020-01-02 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191224_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultuser',
            name='reminder',
        ),
        migrations.AlterField(
            model_name='vault',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Folder'),
        ),
    ]
