// Key & Token
export const GET_TOKEN = {
    SUCCESS: "GET_TOKEN_SUCCESS",
    FAILURE: "GET_TOKEN_FAILURE",
}

export const GET_KEY = {
    SUCCESS: "GET_KEY_SUCCESS",
}

// Login-Logout
export const LOGIN_USER = {
    SUCCESS: "LOGIN_USER_SUCCESS",
    FAILURE: "LOGIN_USER_FAILURE",
}

export const LOGOUT_USER = {
    SUCCESS: "LOGOUT_USER_SUCCESS",
}

// Vault Actions
export const FETCH_VAULTS = {
    SUCCESS: "FETCH_VAULTS_SUCCESS",
    FAILURE: "FETCH_VAULTS_FAILURE",
    LOADING: "FETCH_VAULTS_LOADING",
}

export const CREATE_VAULTS = {
    SUCCESS: "CREATE_VAULTS_SUCCESS",
    FAILURE: "CREATE_VAULTS_FAILURE",
    LOADING: "CREATE_VAULTS_LOADING",
}

export const UPDATE_VAULTS = {
    SUCCESS: "UPDATE_VAULTS_SUCCESS",
    FAILURE: "UPDATE_VAULTS_FAILURE",
    LOADING: "UPDATE_VAULTS_LOADING",
}

export const DELETE_VAULTS = {
    SUCCESS: "DELETE_VAULTS_SUCCESS",
    FAILURE: "DELETE_VAULTS_FAILURE",
    LOADING: "DELETE_VAULTS_LOADING",
}

// Folder Actions
export const FETCH_FOLDERS = {
    SUCCESS: "FETCH_FOLDERS_SUCCESS",
    FAILURE: "FETCH_FOLDERS_FAILURE",
    LOADING: "FETCH_FOLDERS_LOADING",
}

export const CREATE_FOLDER = {
    SUCCESS: "CREATE_FOLDER_SUCCESS",
    FAILURE: "CREATE_FOLDER_FAILURE",
    LOADING: "CREATE_FOLDER_LOADING",
}

export const UPDATE_FOLDER = {
    SUCCESS: "UPDATE_FOLDER_SUCCESS",
    FAILURE: "UPDATE_FOLDER_FAILURE",
    LOADING: "UPDATE_FOLDER_LOADING",
}

export const DELETE_FOLDER = {
    SUCCESS: "DELETE_FOLDER_SUCCESS",
    FAILURE: "DELETE_FOLDER_FAILURE",
    LOADING: "DELETE_FOLDER_LOADING",
}

// User Actions
export const FETCH_USER = {
    SUCCESS: "FETCH_USER_SUCCESS",
    FAILURE: "FETCH_USER_FAILURE",
    LOADING: "FETCH_USER_LOADING",
}

export const CREATE_USER = {
    SUCCESS: "CREATE_USER_SUCCESS",
    FAILURE: "CREATE_USER_FAILURE",
    LOADING: "CREATE_USER_LOADING",
}

export const UPDATE_USER = {
    SUCCESS: "UPDATE_USER_SUCCESS",
    FAILURE: "UPDATE_USER_FAILURE",
    LOADING: "UPDATE_USER_LOADING",
}

export const DELETE_USER = {
    SUCCESS: "DELETE_USER_SUCCESS",
    FAILURE: "DELETE_USER_FAILURE",
    LOADING: "DELETE_USER_LOADING",
}