# Generated by Django 3.0 on 2019-12-24 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VaultItem',
            new_name='Vault',
        ),
        migrations.RemoveField(
            model_name='vaultuser',
            name='mobile',
        ),
    ]
